In [1]:
import torch
import torch._dynamo as dynamo

from air.backend import linalg_on_tensors as backend

In [2]:
SIZE = [128,128]
DTYPE = torch.int32

class MMult_Mult(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, a, b, c):
        x = torch.mm(b,c)
        y = a*x
        return y

In [3]:
air_backend = backend.make_dynamo_backend()

In [4]:
a = torch.randint(100, SIZE, dtype=DTYPE)
b = torch.randint(100, SIZE, dtype=DTYPE)
c = torch.randint(100, SIZE, dtype=DTYPE)

model = MMult_Mult()

In [5]:
# run the model on the device
dynamo_model = dynamo.optimize(air_backend)(model)
result = dynamo_model(a, b, c)

# print the results
print(f"input:\n{a}\n{b}\n{c}\noutput:\n{result}")

 AIE Compilation: ━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:02 17/17 1 Workers
 AIE Compilation: ━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00 5/5 1 Workers
input:
tensor([[36, 72, 56,  ..., 92, 96, 45],
        [20, 33,  5,  ..., 86, 35, 28],
        [24, 60, 64,  ..., 79, 17,  9],
        ...,
        [33, 40, 64,  ..., 66, 75, 74],
        [68, 92, 11,  ..., 37, 33, 65],
        [69, 98, 37,  ..., 26, 31, 41]], dtype=torch.int32)
tensor([[76, 25, 28,  ..., 90, 12,  2],
        [87, 31, 22,  ..., 66, 17, 22],
        [96, 11, 38,  ..., 45, 68, 59],
        ...,
        [30, 92, 82,  ..., 51, 31, 16],
        [15, 25, 63,  ..., 65,  0, 52],
        [83, 33, 49,  ..., 20, 45, 58]], dtype=torch.int32)
tensor([[55,  1, 51,  ..., 27, 82, 87],
        [90, 42, 89,  ..., 76, 60, 89],
        [68,  6, 66,  ...,  6, 86, 44],
        ...,
        [89, 38, 15,  ..., 21, 11, 61],
        [56, 25, 47,  ..., 44, 47, 27],
        [47, 51, 30,  ..., 17, 50, 22]], dtype=torch.int32)
output:
tens

In [6]:
# check the results
if torch.equal(a*torch.mm(b,c),result):
    print("PASS!")
else:
    print("failed.")

PASS!


Copyright (C) 2023, Advanced Micro Devices, Inc. All rights reserved.

SPDX-License-Identifier: MIT